"""create canonical persistence schema

Revision ID: ff7f74e1aa8b
Revises:
Create Date: 2026-08-16 22:38:10.787923
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ff7f74e1aa8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_records",
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_target_time",
        "audit_records",
        ["target_type", "target_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "cameras",
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("zones", sa.JSON(), nullable=False),
        sa.Column("privacy_policy", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "name", name="uq_cameras_site_name"),
    )
    op.create_table(
        "context_snapshots",
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_context_subject_captured",
        "context_snapshots",
        ["subject_type", "captured_at"],
        unique=False,
    )
    op.create_table(
        "model_invocations",
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("runtime_version", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("privacy_route", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_units", sa.Integer(), nullable=True),
        sa.Column("output_units", sa.Integer(), nullable=True),
        sa.Column("cost_micros", sa.Integer(), nullable=True),
        sa.Column("result_hash", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("dedupe_key", sa.String(length=512), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_outbox_dedupe_key"),
    )
    op.create_index(
        "ix_outbox_unpublished", "outbox_events", ["published_at", "created_at"], unique=False
    )
    op.create_table(
        "source_instances",
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=True),
        sa.Column("adapter_version", sa.String(length=128), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("config_ref", sa.String(length=512), nullable=True),
        sa.Column("trust_boundary", sa.String(length=64), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "health_status IN ('starting','healthy','degraded','offline','stopped')",
            name="ck_source_instances_health_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "name", name="uq_source_instances_type_name"),
    )
    op.create_table(
        "decisions",
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("policy_id", sa.String(length=255), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("context_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_decision_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("rule_trace", sa.JSON(), nullable=False),
        sa.Column("evidence_unavailable", sa.Boolean(), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("degraded_reasons", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('send','suppress','enrich','escalate','hold','no_action')",
            name="ck_decision_outcome",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_decision_revision_positive"),
        sa.ForeignKeyConstraint(
            ["context_snapshot_id"], ["context_snapshots.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["supersedes_decision_id"], ["decisions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "revision", name="uq_decision_subject_revision"),
    )
    op.create_table(
        "ingest_checkpoints",
        sa.Column("source_instance_id", sa.Uuid(), nullable=False),
        sa.Column("stream", sa.String(length=512), nullable=False),
        sa.Column("cursor", sa.String(length=1024), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_instance_id"], ["source_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_instance_id", "stream", name="uq_ingest_checkpoint_stream"),
    )
    op.create_table(
        "raw_source_messages",
        sa.Column("source_instance_id", sa.Uuid(), nullable=False),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=512), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("dedupe_key", sa.String(length=512), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quarantined", sa.Boolean(), nullable=False),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_instance_id"], ["source_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_instance_id", "dedupe_key", name="uq_raw_source_dedupe"),
    )
    op.create_index(
        "ix_raw_source_observed_at",
        "raw_source_messages",
        ["source_instance_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "review_items",
        sa.Column("camera_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("zones", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','ended','corrected','deleted')", name="ck_review_status"
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_camera_start", "review_items", ["camera_id", "start_at"], unique=False
    )
    op.create_table(
        "source_entity_maps",
        sa.Column("source_instance_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("source_entity_id", sa.String(length=512), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("internal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_instance_id"], ["source_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_instance_id",
            "namespace",
            "source_entity_id",
            name="uq_source_entity_external_identity",
        ),
    )
    op.create_index(
        "ix_source_entity_internal",
        "source_entity_maps",
        ["entity_type", "internal_entity_id"],
        unique=False,
    )
    op.create_table(
        "actions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned','running','succeeded','retryable_failure','permanent_failure')",
            name="ck_actions_status",
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_actions_idempotency_key"),
    )
    op.create_table(
        "feedback",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("supersedes_feedback_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verdict IN ('important','not_important','false_positive','uncertain')",
            name="ck_feedback_verdict",
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_feedback_id"], ["feedback.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "observations",
        sa.Column("source_instance_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.Uuid(), nullable=True),
        sa.Column("raw_message_id", sa.Uuid(), nullable=True),
        sa.Column("source_namespace", sa.String(length=128), nullable=False),
        sa.Column("source_entity_id", sa.String(length=512), nullable=False),
        sa.Column("source_revision", sa.String(length=128), nullable=False),
        sa.Column("dedupe_key", sa.String(length=512), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("event_kind", sa.String(length=32), nullable=False),
        sa.Column("lifecycle", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("partial_history", sa.Boolean(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("zones", sa.JSON(), nullable=False),
        sa.Column("extensions", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_kind IN ('review','object','motion','audio','sensor','system','unknown')",
            name="ck_observations_event_kind",
        ),
        sa.CheckConstraint(
            "lifecycle IN ('started','updated','ended','corrected','deleted')",
            name="ck_observations_lifecycle",
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["raw_message_id"], ["raw_source_messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_instance_id"], ["source_instances.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_instance_id", "dedupe_key", name="uq_observations_dedupe"),
    )
    op.create_index(
        "ix_observations_camera_occurred",
        "observations",
        ["camera_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_observations_source_entity",
        "observations",
        ["source_instance_id", "source_namespace", "source_entity_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("observation_id", sa.Uuid(), nullable=True),
        sa.Column("model_invocation_id", sa.Uuid(), nullable=True),
        sa.Column("producer_type", sa.String(length=32), nullable=False),
        sa.Column("producer_version", sa.String(length=128), nullable=False),
        sa.Column("predicate", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("evidence_unavailable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_claim_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"], ["model_invocations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("source_instance_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=True),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=1024), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("privacy_class", sa.String(length=32), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "availability IN ('available','pending','expired','denied','unknown')",
            name="ck_evidence_availability",
        ),
        sa.CheckConstraint(
            "privacy_class IN ('local_only','cloud_redacted','cloud_allowed')",
            name="ck_evidence_privacy_class",
        ),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_instance_id"], ["source_instances.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_instance_id", "source_ref", name="uq_evidence_source_ref"),
    )
    op.create_table(
        "notifications",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("external_message_id", sa.String(length=512), nullable=True),
        sa.Column("delivery_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "stage IN ('initial','enhanced','resolved','escalated')", name="ck_notification_stage"
        ),
        sa.ForeignKeyConstraint(["action_id"], ["actions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "idempotency_key", name="uq_notification_channel_key"),
    )
    op.create_table(
        "observed_objects",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("sub_labels", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("stationary", sa.Boolean(), nullable=True),
        sa.Column("track", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_observed_object_confidence",
        ),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observation_id", "object_key", name="uq_observed_object_key"),
    )
    op.create_table(
        "review_observations",
        sa.Column("review_item_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_item_id"], ["review_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_item_id", "observation_id"),
    )
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id"),
    )
    op.create_table(
        "decision_claims",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("decision_id", "claim_id"),
    )
    op.create_table(
        "decision_evidence",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("decision_id", "evidence_id"),
    )
    op.create_table(
        "model_invocation_evidence",
        sa.Column("model_invocation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"], ["model_invocations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("model_invocation_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_invocation_evidence")
    op.drop_table("decision_evidence")
    op.drop_table("decision_claims")
    op.drop_table("claim_evidence")
    op.drop_table("review_observations")
    op.drop_table("observed_objects")
    op.drop_table("notifications")
    op.drop_table("evidence")
    op.drop_table("claims")
    op.drop_index("ix_observations_source_entity", table_name="observations")
    op.drop_index("ix_observations_camera_occurred", table_name="observations")
    op.drop_table("observations")
    op.drop_table("feedback")
    op.drop_table("actions")
    op.drop_index("ix_source_entity_internal", table_name="source_entity_maps")
    op.drop_table("source_entity_maps")
    op.drop_index("ix_review_camera_start", table_name="review_items")
    op.drop_table("review_items")
    op.drop_index("ix_raw_source_observed_at", table_name="raw_source_messages")
    op.drop_table("raw_source_messages")
    op.drop_table("ingest_checkpoints")
    op.drop_table("decisions")
    op.drop_table("source_instances")
    op.drop_index("ix_outbox_unpublished", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("model_invocations")
    op.drop_index("ix_context_subject_captured", table_name="context_snapshots")
    op.drop_table("context_snapshots")
    op.drop_table("cameras")
    op.drop_index("ix_audit_target_time", table_name="audit_records")
    op.drop_table("audit_records")
    # ### end Alembic commands ###
